wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.7.7
    start_time: 1657618452
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 63
      - 74
      2:
      - 1
      - 9
      - 41
      - 55
      - 63
      - 74
      3:
      - 7
      - 13
      4: 3.7.7
      5: 0.12.21
      8:
      - 2
      - 5
