wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.7
    start_time: 1657611103
    t:
      1:
      - 1
      - 9
      3:
      - 13
      4: 3.7.7
      5: 0.12.9
      8:
      - 2
      - 5
