wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_per_image_iou
      5: 1
      6:
      - 1
    - 1: val_dataset_iou
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.7.7
    start_time: 1657610826
    t:
      1:
      - 1
      - 9
      3:
      - 13
      4: 3.7.7
      5: 0.12.9
      8:
      - 2
      - 5
